"""updated

Revision ID: 07c3e8fdfe0e
Revises: 6fd8fba0070b
Create Date: 2021-03-16 11:24:37.490311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c3e8fdfe0e'
down_revision = '6fd8fba0070b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=50), nullable=True),
    sa.Column('about', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('img', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
