"""Yeni table yaradildi

Revision ID: 10158dca188d
Revises: 
Create Date: 2021-03-13 17:45:34.980942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10158dca188d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=True),
    sa.Column('about', sa.String(length=1000), nullable=True),
    sa.Column('img', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('about')
    # ### end Alembic commands ###
