"""table deyistirildi

Revision ID: 4f123eeda410
Revises: 6b3d29b5cd7b
Create Date: 2021-03-16 11:20:43.425510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f123eeda410'
down_revision = '6b3d29b5cd7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('img', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
