"""updated

Revision ID: 6fd8fba0070b
Revises: 4f123eeda410
Create Date: 2021-03-16 11:22:17.698314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd8fba0070b'
down_revision = '4f123eeda410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('about')
    op.drop_column('authors', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('img', sa.VARCHAR(length=50), nullable=True))
    op.create_table('about',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=50), nullable=True),
    sa.Column('about', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('img', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
